name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install devkitARM toolchain
      run: |
        sudo apt update
        sudo apt install -y curl gnupg
        echo "deb https://apt.devkitpro.org stable main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
        curl https://apt.devkitpro.org/devkitpro-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/devkitpro-archive-keyring.gpg
        sudo apt update
        sudo apt install -y devkitarm

    - name: make
      run: make all

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: |
          TJAP_3DS.3dsx
          TJAP_3DS.cia
