name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install devkitARM
      uses: devkitPro/actions/devkitarm-install@v1

    - name: make
      run: make all

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: |
          TJAP_3DS.3dsx
          TJAP_3DS.cia
